In [292]:
import pandas as pd

In [293]:
df = pd.read_csv("my_file (1).csv")

In [294]:
type(df)

pandas.DataFrame

In [295]:
df.head(20)

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,2[4],NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]
5,6,2[4],10[9],"$305,158,363","$388,978,496",Madonna,The MDNA Tour,2012,88,"$3,467,709",[9]
6,7,2[10],NaN,"$280,000,000","$381,932,682",Celine Dion,Taking Chances World Tour,2008–2009,131,"$2,137,405",[11]
7,7,NaN,NaN,"$257,600,000","$257,600,000",Pink,Summer Carnival †,2023–2024,41,"$6,282,927",[12]
8,9,NaN,NaN,"$256,084,556","$312,258,401",Beyoncé,The Formation World Tour,2016,49,"$5,226,215",[13]
9,10,NaN,NaN,"$250,400,000","$309,141,878",Taylor Swift,The 1989 World Tour,2015,85,"$2,945,882",[14]
10,11,NaN,NaN,"$229,100,000[b]","$283,202,896",Beyoncé,The Mrs. Carter Show World Tour,2013–2014,132,"$1,735,606",[15][16]
11,12,NaN,14[17],"$227,400,000","$295,301,479",Lady Gaga,The Monster Ball Tour *,2009–2011,203,"$1,118,227",[18]
12,13,NaN,NaN,"$204,000,000","$251,856,802",Katy Perry,Prismatic World Tour,2014–2015,151,"$1,350,993",[19]
13,14,1[20],NaN,"$200,000,000","$299,676,265",Cher,Living Proof: The Farewell Tour ‡[21][a],2002–2005,325,"$615,385",[20]
14,15,2[c],NaN,"$194,000,000","$281,617,035",Madonna,Confessions Tour,2006,60,"$3,233,333",[5]
15,16,NaN,NaN,"$184,000,000","$227,452,347",Pink,The Truth About Love Tour,2013–2014,142,"$1,295,775",[22]
16,17,NaN,NaN,"$170,000,000","$213,568,571",Lady Gaga,Born This Way Ball,2012–2013,98,"$1,734,694",[d]
17,18,NaN,NaN,"$169,800,000","$207,046,755",Madonna,Rebel Heart Tour,2015–2016,82,"$2,070,732",[4]
18,19,NaN,NaN,"$167,700,000[e]","$204,486,106",Adele,Adele Live 2016,2016–2017,121,"$1,385,950",[25]
19,20,NaN,NaN,"$150,000,000","$185,423,109",Taylor Swift,The Red Tour,2013–2014,86,"$1,744,186",[26]

In [296]:
df.columns

Index(['Rank', 'Peak', 'All Time Peak', 'Actual gross',
       'Adjusted gross (in 2022 dollars)', 'Artist', 'Tour title', 'Year(s)',
       'Shows', 'Average gross', 'Ref.'],
      dtype='str')

In [297]:
df.columns = (df.columns.str.lower()
                .str.replace(" ", "_")
                .str.replace("\xa0", "_")
                .str.replace(r"[^\w]", ""))
df[["actual_gross", "average_gross", "adjusted_gross_(in_2022_dollars)"]] = df[["actual_gross", "average_gross", "adjusted_gross_(in_2022_dollars)"]].replace(r"[^0-9]", "", regex=True)
df["tour_title"] = df["tour_title"].str.replace(r"\[.*?\]","", regex = True).str.replace(r"[^\w]", "", regex = True).str.strip()

In [298]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   rank                              20 non-null     int64
 1   peak                              9 non-null      str
 2   all_time_peak                     6 non-null      str
 3   actual_gross                      20 non-null     str
 4   adjusted_gross_(in_2022_dollars)  20 non-null     str
 5   artist                            20 non-null     str
 6   tour_title                        20 non-null     str
 7   year(s)                           20 non-null     str
 8   shows                             20 non-null     int64
 9   average_gross                     20 non-null     str
 10  ref.                              20 non-null     str
dtypes: int64(2), str(9)
memory usage: 1.8 KB

In [299]:
df.drop(columns=["peak", "all_time_peak"] ,inplace=True)

In [300]:
df[['ref.']].T
#useless column
df.drop(columns=['ref.'], inplace= True)

In [301]:
df.head(20)

,rank,actual_gross,adjusted_gross_(in_2022_dollars),artist,tour_title,year(s),shows,average_gross
0,1,780000000,780000000,Taylor Swift,TheErasTour,2023–2024,56,13928571
1,2,579800000,579800000,Beyoncé,RenaissanceWorldTour,2023,56,10353571
2,3,411000000,560622615,Madonna,StickySweetTour,2008–2009,85,4835294
3,4,397300000,454751555,Pink,BeautifulTraumaWorldTour,2018–2019,156,2546795
4,5,345675146,402844849,Taylor Swift,ReputationStadiumTour,2018,53,6522173
5,6,305158363,388978496,Madonna,TheMDNATour,2012,88,3467709
6,7,280000000,381932682,Celine Dion,TakingChancesWorldTour,2008–2009,131,2137405
7,7,257600000,257600000,Pink,SummerCarnival,2023–2024,41,6282927
8,9,256084556,312258401,Beyoncé,TheFormationWorldTour,2016,49,5226215
9,10,250400000,309141878,Taylor Swift,The1989WorldTour,2015,85,2945882
10,11,229100000,283202896,Beyoncé,TheMrsCarterShowWorldTour,2013–2014,132,1735606
11,12,227400000,295301479,Lady Gaga,TheMonsterBallTour,2009–2011,203,1118227
12,13,204000000,251856802,Katy Perry,PrismaticWorldTour,2014–2015,151,1350993
13,14,200000000,299676265,Cher,LivingProofTheFarewellTour,2002–2005,325,615385
14,15,194000000,281617035,Madonna,ConfessionsTour,2006,60,3233333
15,16,184000000,227452347,Pink,TheTruthAboutLoveTour,2013–2014,142,1295775
16,17,170000000,213568571,Lady Gaga,BornThisWayBall,2012–2013,98,1734694
17,18,169800000,207046755,Madonna,RebelHeartTour,2015–2016,82,2070732
18,19,167700000,204486106,Adele,AdeleLive2016,2016–2017,121,1385950
19,20,150000000,185423109,Taylor Swift,TheRedTour,2013–2014,86,1744186

In [302]:

newyears = df["year(s)"].str.split("–", expand= True)

In [303]:
newyears

       0     1
0   2023  2024
1   2023   NaN
2   2008  2009
3   2018  2019
4   2018   NaN
5   2012   NaN
6   2008  2009
7   2023  2024
8   2016   NaN
9   2015   NaN
10  2013  2014
11  2009  2011
12  2014  2015
13  2002  2005
14  2006   NaN
15  2013  2014
16  2012  2013
17  2015  2016
18  2016  2017
19  2013  2014

In [304]:
df = df.rename(columns={"year(s)" : "start_year"})
df["start_year"] = newyears[0]
df["end_year"] = newyears[1]

In [305]:
col_end = df.pop("end_year")
df.insert(6, "end_year", col_end)
df['end_year'] = df['end_year'].fillna(df['start_year'])

In [308]:
df.to_csv("cleaned", index=False)