In [12]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd

In [13]:
df = pd.read_csv("sample_data.csv")

In [14]:
df_label = df.copy()
df_label['Gender_Encoded'] = LabelEncoder().fit_transform(df_label['Gender'])
df_label['Passed_Encoded'] = LabelEncoder().fit_transform(df_label['Passed'])

In [15]:
df_label['Gender_Encoded']

0     1
1     0
2     1
3     0
4     1
5     0
6     1
7     0
8     1
9     0
10    1
11    0
12    1
13    0
14    1
15    0
16    1
17    0
18    1
19    0
Name: Gender_Encoded, dtype: int64

In [16]:
df_label['Passed_Encoded']

0     1
1     1
2     0
3     1
4     1
5     0
6     1
7     1
8     0
9     1
10    1
11    0
12    1
13    1
14    0
15    1
16    1
17    0
18    1
19    1
Name: Passed_Encoded, dtype: int64

In [17]:
df_label.head()

     Name  Gender       City Passed  Gender_Encoded  Passed_Encoded
0    Aman    Male      Delhi    Yes               1               1
1   Priya  Female     Mumbai    Yes               0               1
2   Rahul    Male  Bangalore     No               1               0
3  Anjali  Female     Mumbai    Yes               0               1
4    Ravi    Male      Delhi    Yes               1               1

In [18]:
df_encoded = pd.get_dummies(df_label, columns=['City'])

In [19]:
print(df_encoded)

      Name  Gender Passed  Gender_Encoded  Passed_Encoded  City_Bangalore  \
0     Aman    Male    Yes               1               1           False
1    Priya  Female    Yes               0               1           False
2    Rahul    Male     No               1               0            True
3   Anjali  Female    Yes               0               1           False
4     Ravi    Male    Yes               1               1           False
5    Meera  Female     No               0               0           False
6    Arjun    Male    Yes               1               1            True
7     Neha  Female    Yes               0               1           False
8    Imran    Male     No               1               0           False
9    Sneha  Female    Yes               0               1           False
10     Raj    Male    Yes               1               1           False
11   Divya  Female     No               0               0           False
12   Kabir    Male    Yes               1               1           False
13  Simran  Female    Yes               0               1            True
14   Karan    Male     No               1               0           False
15   Pooja  Female    Yes               0               1           False
16  Rakesh    Male    Yes               1               1           False
17    Isha  Female     No               0               0           False
18   Rohit    Male    Yes               1               1           False
19   Deepa  Female    Yes               0               1            True

    City_Chennai  City_Delhi  City_Mumbai
0          False        True        False
1          False       False         True
2          False       False        False
3          False       False         True
4          False        True        False
5           True       False        False
6          False       False        False
7          False        True        False
8           True       False        False
9          False       False         True
10          True       False        False
11         False        True        False
12         False       False         True
13         False       False        False
14         False        True        False
15         False       False         True
16          True       False        False
17         False        True        False
18         False        True        False
19         False       False        False

In [20]:
df_encoded = df_encoded.replace({True:1, False: 0})

In [21]:
df_encoded

,Name,Gender,Passed,Gender_Encoded,Passed_Encoded,City_Bangalore,City_Chennai,City_Delhi,City_Mumbai
0,Aman,Male,Yes,1,1,0,0,1,0
1,Priya,Female,Yes,0,1,0,0,0,1
2,Rahul,Male,No,1,0,1,0,0,0
3,Anjali,Female,Yes,0,1,0,0,0,1
4,Ravi,Male,Yes,1,1,0,0,1,0
5,Meera,Female,No,0,0,0,1,0,0
6,Arjun,Male,Yes,1,1,1,0,0,0
7,Neha,Female,Yes,0,1,0,0,1,0
8,Imran,Male,No,1,0,0,1,0,0
9,Sneha,Female,Yes,0,1,0,0,0,1
10,Raj,Male,Yes,1,1,0,1,0,0
11,Divya,Female,No,0,0,0,0,1,0
12,Kabir,Male,Yes,1,1,0,0,0,1
13,Simran,Female,Yes,0,1,1,0,0,0
14,Karan,Male,No,1,0,0,0,1,0
15,Pooja,Female,Yes,0,1,0,0,0,1
16,Rakesh,Male,Yes,1,1,0,1,0,0
17,Isha,Female,No,0,0,0,0,1,0
18,Rohit,Male,Yes,1,1,0,0,1,0
19,Deepa,Female,Yes,0,1,1,0,0,0

In [22]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split

data = {
    'Study Hours': [1,2,3,4,5],
    'Test Score': [40, 50, 60, 70, 80]
}

df = pd.DataFrame(data)
standScalar = StandardScaler()
standScalar = standScalar.fit_transform(df) 
print(data)
print(standScalar)

{'Study Hours': [1, 2, 3, 4, 5], 'Test Score': [40, 50, 60, 70, 80]}
[[-1.41421356 -1.41421356]
 [-0.70710678 -0.70710678]
 [ 0.          0.        ]
 [ 0.70710678  0.70710678]
 [ 1.41421356  1.41421356]]