In [69]:
import pandas as pd

In [70]:
df = pd.read_csv("Diwali Sales Data.csv", encoding='unicode_escape')
df.head()

,User_ID,Cust_name,Product_ID,Gender,Age Group,Age,Marital_Status,State,Zone,Occupation,Product_Category,Orders,Amount,Status,unnamed1
0,1002903,Sanskriti,P00125942,F,26-35,28,0,Maharashtra,Western,Healthcare,Auto,1,23952.0,NaN,NaN
1,1000732,Kartik,P00110942,F,26-35,35,1,Andhra Pradesh,Southern,Govt,Auto,3,23934.0,NaN,NaN
2,1001990,Bindu,P00118542,F,26-35,35,1,Uttar Pradesh,Central,Automobile,Auto,3,23924.0,NaN,NaN
3,1001425,Sudevi,P00237842,M,0-17,16,0,Karnataka,Southern,Construction,Auto,2,23912.0,NaN,NaN
4,1000588,Joni,P00057942,M,26-35,28,1,Gujarat,Western,Food Processing,Auto,2,23877.0,NaN,NaN

In [71]:
df.shape

(11251, 15)

In [72]:
df.isnull().sum()
df.columns

Index(['User_ID', 'Cust_name', 'Product_ID', 'Gender', 'Age Group', 'Age',
       'Marital_Status', 'State', 'Zone', 'Occupation', 'Product_Category',
       'Orders', 'Amount', 'Status', 'unnamed1'],
      dtype='str')

In [73]:
df['unnamed1'].head()

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: unnamed1, dtype: float64

In [74]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 11251 entries, 0 to 11250
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   User_ID           11251 non-null  int64
 1   Cust_name         11251 non-null  str
 2   Product_ID        11251 non-null  str
 3   Gender            11251 non-null  str
 4   Age Group         11251 non-null  str
 5   Age               11251 non-null  int64
 6   Marital_Status    11251 non-null  int64
 7   State             11251 non-null  str
 8   Zone              11251 non-null  str
 9   Occupation        11251 non-null  str
 10  Product_Category  11251 non-null  str
 11  Orders            11251 non-null  int64
 12  Amount            11239 non-null  float64
 13  Status            0 non-null      float64
 14  unnamed1          0 non-null      float64
dtypes: float64(3), int64(4), str(8)
memory usage: 1.3 MB

In [75]:
df.drop( ['Status', 'unnamed1'], axis= 1, inplace= True)
df.columns

Index(['User_ID', 'Cust_name', 'Product_ID', 'Gender', 'Age Group', 'Age',
       'Marital_Status', 'State', 'Zone', 'Occupation', 'Product_Category',
       'Orders', 'Amount'],
      dtype='str')

In [89]:
df.dropna(inplace= True)
df.info()

<class 'pandas.DataFrame'>
Index: 11239 entries, 0 to 11250
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   User_ID           11239 non-null  int64
 1   Cust_name         11239 non-null  str
 2   Product_ID        11239 non-null  str
 3   Gender            11239 non-null  str
 4   Age Group         11239 non-null  str
 5   Age               11239 non-null  int64
 6   Marital_Status    11239 non-null  int64
 7   State             11239 non-null  str
 8   Zone              11239 non-null  str
 9   Occupation        11239 non-null  str
 10  Product_Category  11239 non-null  str
 11  Orders            11239 non-null  int64
 12  Amount            11239 non-null  int64
dtypes: int64(5), str(8)
memory usage: 1.2 MB

In [90]:
print(df['Amount'].head())
df['Amount'] = df['Amount'].astype('int')
df['Amount'].dtypes

0    23952
1    23934
2    23924
3    23912
4    23877
Name: Amount, dtype: int64

dtype('int64')

In [91]:
df.head()

,User_ID,Cust_name,Product_ID,Gender,Age Group,Age,Marital_Status,State,Zone,Occupation,Product_Category,Orders,Amount
0,1002903,Sanskriti,P00125942,F,26-35,28,0,Maharashtra,Western,Healthcare,Auto,1,23952
1,1000732,Kartik,P00110942,F,26-35,35,1,Andhra Pradesh,Southern,Govt,Auto,3,23934
2,1001990,Bindu,P00118542,F,26-35,35,1,Uttar Pradesh,Central,Automobile,Auto,3,23924
3,1001425,Sudevi,P00237842,M,0-17,16,0,Karnataka,Southern,Construction,Auto,2,23912
4,1000588,Joni,P00057942,M,26-35,28,1,Gujarat,Western,Food Processing,Auto,2,23877

In [103]:
df.loc[0, 'Age'] = 20
df.loc[0, 'State'] = 'Lahore'
df.groupby('State')['Age'].min()

State
Andhra Pradesh      12
Bihar               12
Delhi               12
Gujarat             12
Haryana             12
Himachal Pradesh    12
Jharkhand           12
Karnataka           12
Kerala              12
Lahore              20
Madhya Pradesh      12
Maharashtra         12
Punjab              12
Rajasthan           12
Telangana           15
Uttar Pradesh       12
Uttarakhand         12
Name: Age, dtype: int64